### PR TITLE
Picking multiple presentors at once

### PR DESCRIPTION
**Pull request by kpasma**
Added the option to pick and present multiple presentors at once.
Also did some clean up:
The old members were still included in the weights dictionary. Although their weights were always zero, it cluttered the dictionary. This made it harder to debug. Now they are not taken into consideration.

### CODE REVIEW

**Comment by moorepants** [comment]
I thought the issue for choosing two presenters is that when you make the second choice the first chosen is not eliminated from the selection list. It isn't clear to me that that issue is addressed.

**Comment by kpasma** [comment]
The latest commit should fix the comment you made.
The chosen presenter is removed from the list for the next selection of presenter.

**Comment by moorepants** [comment]
Looks like this now has conflicts with master. Can you resolve and then I'll merge it?

**Comment by kpasma** [comment]
Done

**Pull request merged**
